version: "3"
services: 
  angular:
    build: frontend
    ports:
      - "4300:4200"
  express:
    build: backend
    ports:
      - "8080:5000"
    links: 
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27017:27017"